application: pymntos
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
  
- url: /javascript
  static_dir: static/javascript
  
- url: /styles
  static_dir: static/styles
  
- url: /.*
  script: apps/app.py
