application: minnepy
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
  
- url: /javascript
  static_dir: static/javascript
  
- url: /styles
  static_dir: static/styles
  
- url: /
  script: apps/minnepy.py
  
- url: /calendar.*
  script: apps/calendar.py
  
- url: /blog.*
  script: apps/blog.py
  
- url: /blogs.*
  script: apps/blog.py